console.log("Hi there!");
console.log("I am excited to talk to you.");
let bot;
bot = "teacherBot";
let botLocation = "the universe";
console.log("Allow me to introduce myself.");
let botIntroduction;
botIntroduction = "My name is " + bot + ".";
console.log(botIntroduction);
const botLocationSentence = "I live in " + botLocation + ".";
console.log(botLocationSentence);
